language: python
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y make sed
install:
  - pip install tox
matrix:
  include:
    - python: "2.7"
      env: TOX_ENVS=py27-django18,py27-django19,py27-django110,py27-django111
    - python: "3.4"
      env: TOX_ENVS=py34-django18,py34-django19,py34-django110,py34-django111,py34-django2,lint
    - python: "3.6"
      env: TOX_ENVS=py36-django111,py36-django2,py36-django2
    - python: "3.5"
      env: TOX_ENVS=py35-django18,py35-django19,py35-django110,py35-django111,py35-django2
    - python: "3.3"
      env: TOX_ENVS=py33-django18
script:
  - tox -e $TOX_ENVS
